name: EncChat CI/CD Pipeline

on:
  push:
    branches: [ main, Patryk, Kacper, Pawel ]
  pull_request:
    branches: [ main ]

jobs:
  project-setup:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Debug directory structure
      run: |
        echo "Current directory: $(pwd)"
        echo "Contents of current directory:"
        ls -la
        echo ""
        echo "Searching for package.json files:"
        find . -name "package.json" | sort
        echo ""
        echo "Searching for directories with 'backend' in the name:"
        find . -type d -name "*backend*" | sort
        echo ""
        echo "Repository structure:"
        find . -type d -not -path "*/node_modules/*" -not -path "*/.git/*" | sort

  build:
    needs: project-setup
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install root dependencies
      run: |
        if [ -f "package.json" ]; then
          npm ci || npm install
        else
          echo "No package.json found in the root directory"
        fi
    
    - name: Install backend dependencies
      run: |
        if [ -d "backend" ]; then
          cd backend
          if [ -f "package.json" ]; then
            npm ci || npm install
          else
            echo "No package.json found in the backend directory"
          fi
        elif [ -d "EncChat/backend" ]; then
          cd EncChat/backend
          if [ -f "package.json" ]; then
            npm ci || npm install
          else
            echo "No package.json found in the EncChat/backend directory"
          fi
        else
          echo "Could not find the backend directory"
        fi
    
    - name: Build project
      run: |
        if [ -f "package.json" ]; then
          npm run build || echo "No build script in root package.json"
        elif [ -d "src" ] && [ -f "src/package.json" ]; then
          cd src
          npm ci || npm install
          npm run build || echo "No build script in src/package.json"
        elif [ -d "EncChat/src" ] && [ -f "EncChat/src/package.json" ]; then
          cd EncChat/src
          npm ci || npm install
          npm run build || echo "No build script in EncChat/src/package.json"
        else
          echo "Could not find a suitable directory with package.json for building"
        fi
    
    - name: Create artifact directory
      run: |
        mkdir -p artifacts
        
        # Look for build directories and copy contents if found
        for dir in "./build" "./dist" "./src/build" "./src/dist" "./EncChat/build" "./EncChat/dist" "./EncChat/src/build" "./EncChat/src/dist"; do
          if [ -d "$dir" ]; then
            echo "Found build directory at $dir, copying contents to artifacts/"
            cp -r "$dir"/* artifacts/ || echo "No files to copy from $dir"
          fi
        done
        
        # If no build directory was found, create a placeholder file
        if [ -z "$(ls -A artifacts/)" ]; then
          echo "No build artifacts found, creating placeholder file"
          echo "This is a placeholder for build artifacts" > artifacts/placeholder.txt
        fi
        
        echo "Final artifacts directory contents:"
        ls -la artifacts/
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: artifacts
        if-no-files-found: warn

  deploy-development:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/Patryk' || github.ref == 'refs/heads/Kacper' || github.ref == 'refs/heads/Pawel'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: artifacts
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Deploy to development
      run: |
        echo "Deploying to development environment..."
        echo "Working directory: $(pwd)"
        echo "Contents of artifacts directory:"
        ls -la artifacts/
        
        echo "Using environment variables for configuration"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        EMAILJS_PRIVATE_KEY: ${{ secrets.EMAILJS_PRIVATE_KEY }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        EMAILJS_RESET_PASSWORD_TEMPLATE: ${{ secrets.EMAILJS_RESET_PASSWORD_TEMPLATE }}
        EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        EMAILJS_VERIFY_EMAIL_TEMPLATE: ${{ secrets.EMAILJS_VERIFY_EMAIL_TEMPLATE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}

  deploy-production:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: artifacts
    
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Deploy to production
      run: |
        echo "Deploying to production environment..."
        echo "Working directory: $(pwd)"
        echo "Contents of artifacts directory:"
        ls -la artifacts/
        
        echo "Using environment variables for configuration"
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
        CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
        EMAILJS_PRIVATE_KEY: ${{ secrets.EMAILJS_PRIVATE_KEY }}
        EMAILJS_PUBLIC_KEY: ${{ secrets.EMAILJS_PUBLIC_KEY }}
        EMAILJS_RESET_PASSWORD_TEMPLATE: ${{ secrets.EMAILJS_RESET_PASSWORD_TEMPLATE }}
        EMAILJS_SERVICE_ID: ${{ secrets.EMAILJS_SERVICE_ID }}
        EMAILJS_VERIFY_EMAIL_TEMPLATE: ${{ secrets.EMAILJS_VERIFY_EMAIL_TEMPLATE }}
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
